### ISSUE TITLE
Dotty work-around for Expr.Type.ObjBridge creates new Nothing-inferred type runtime error

### ISSUE THREAD

**Issue by Sciss** [Sciss/Lucre#52]
In GitLab by @Sciss on Feb 21, 2021, 21:08

```
[info]   java.lang.ClassCastException: de.sciss.lucre.IntObj$ cannot be cast to scala.runtime.Nothing$
[info]   at de.sciss.lucre.Expr$Type$ObjBridge$.readIdentifiedAdjunct(Expr.scala:61)
[info]   at de.sciss.lucre.Adjunct$.read(Adjunct.scala:55)
[info]   at de.sciss.lucre.Adjunct$.readT(Adjunct.scala:59)
[info]   at de.sciss.lucre.expr.ExElem$RefMapIn.readAdjunct(ExElem.scala:149)
```

apparently, at least with Scala 2.12, the line

```scala
val peerT: Expr.Type[scala.Any, Expr.Any] = peer.asInstanceOf
```

infers `Nothing` on the RHS. D'oh.

(was work-around for https://github.com/lampepfl/dotty/issues/11464 )

**Comment by Sciss** [comment]
In GitLab by @Sciss on Feb 21, 2021, 21:25

mentioned in commit 5d999af5026f0b611be85b81711004adeb2327a4
